'use client';
import Image from 'next/image';
import Link from 'next/link';
import {ArrowUpRight} from 'lucide-react';
import {Avatar,HEADWEAR} from './Identity';
import {Globe} from './Globe';

const stories=[
 {id:'interest',title:'Find your kind of curious.',body:'AI, gaming, everyday brands. Start with an interest and meet the companies—and people—inside it.',tag:'Explore your interests',href:'/app/groups',alt:'Plush Daybreak characters with a glass chip and chrome game controller'},
 {id:'watchlist',title:'Good finds deserve company.',body:'A place for the companies you keep coming back to. Save your favorites today; shared watchlists are on the way.',tag:'Start your collection',href:'/app',alt:'Daybreak characters beside sculptural glass watchlist cards'},
 {id:'culture',title:'A little less serious.',body:'The references. The inside jokes. The memes that make a niche feel like home. Part of our vision for every circle.',tag:'Meet the circles',href:'/app/groups',alt:'Expressive Daybreak heads laughing and winking with a blue speech bubble'},
];
export default function LandingStories(){return <>
 <section className="db-section db-world-section" id="your-world"><div className="db-shell db-world-layout"><div className="db-section-head" data-reveal><span className="db-micro">Small circles. A wider world.</span><h2>Your people.<br/>Everywhere.</h2><p>Different places. Shared obsessions. Find a circle around what you love, from the next wave of technology to the brands in your everyday.</p><Link href="/app/groups" className="db-button db-blue-button">Find your circle <ArrowUpRight size={17}/></Link><span className="db-section-note">Illustrated community. Real member locations are never shown.</span></div><div className="db-community-planet"><Globe speed={0.0012}/><div className="db-planet-head planet-head-0"><Avatar seed={0} size={136}/></div><div className="db-planet-head planet-head-1"><Avatar seed={1} size={122}/></div><div className="db-planet-head planet-head-2"><Avatar seed={2} size={148}/></div><div className="db-planet-head planet-head-3"><Avatar seed={5} size={108}/></div><span className="db-planet-note">A shared interest is a good start.</span></div></div></section>
 <section className="db-section db-stories db-band-blue" id="circle-life"><div className="db-shell"><div className="db-story-heading" data-reveal><span className="db-micro">Life inside your circle</span><h2>Stocks. Stories.<br/>And your kind of people.</h2><p>A first look at where Daybreak is going. Shared watchlists and meme discovery are coming next.</p></div><div className="db-poster-grid">{stories.map(s=><article key={s.id} className="db-poster" data-reveal><div className="db-poster-art"><Image src={`/assets/posters/${s.id}.png`} width={1024} height={1280} sizes="(max-width:700px) 90vw, 33vw" alt={s.alt}/></div><h3>{s.title}</h3><p>{s.body}</p><Link href={s.href} className="db-text-link">{s.tag} <ArrowUpRight size={16}/></Link></article>)}</div></div></section>
 <section className="db-section db-wear-section"><div className="db-shell"><div className="db-wear-heading" data-reveal><div><span className="db-micro">A little personality goes a long way</span><h2>Wear your interests.</h2></div><Link href="/app/profile" className="db-button db-blue-button">Make it yours <ArrowUpRight size={17}/></Link></div><div className="db-wear-lineup">{HEADWEAR.map((h,i)=><Link href="/app/profile" key={h.id} aria-label={`Customize your avatar with ${h.name}`}><Avatar seed={i} size={160}/><span>{h.name}</span></Link>)}</div><p className="db-section-note">Six plush looks. Stock pins that express your taste. No NFT needed.</p></div></section>
 </>}
