'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {memeMoment,pfpArt,bannerArt} from '@/lib/muse/prompt';
import {momentsFor,nostalgiaMoment} from '@/lib/news/nostalgia';
import Link from 'next/link';
import {createPublicClient,http,type Hex} from 'viem';
import {base} from 'viem/chains';
const paymentClient=createPublicClient({chain:base,transport:http('https://mainnet.base.org')});
import {ArrowRight,Check,Download,ImagePlus,LoaderCircle,Plus,Sparkles,X} from 'lucide-react';
import {authedFetch} from '@/lib/account/api-client';
import {TOKENS} from '@/lib/base/tokens';
import {useAccountState} from './AccountProvider';
import {StockIcon} from './Identity';

type Capsule={id:string;name:string;statement:string;cover:string|null;accent:string;status?:string};
type Snapshot={capsules:Capsule[];balance:number;config:{enabled:boolean;mode:string;prices:{forge:number;create:number}};payments:{enabled:boolean;recipient:string;assets:{symbol:string;label:string;address:string}[]}};
type Creation={id:string;status:string;image?:string;error?:string;eligible?:boolean;kind?:string;pull_group?:string|null;moment_lane?:string|null;moment_text?:string|null};
type PullItem={id:string;status:string;kind?:string;ticker?:string;created_at?:string;has_image?:boolean};
type CommunityItem={id:string;ticker:string;image:string};
type Pulls={freeLeft:number;pulls:PullItem[];community:CommunityItem[]};
function useCreationPoll(value:Creation|null,setValue:(c:Creation|null)=>void){const id=value?.id;const status=value?.status;useEffect(()=>{if(status!=='pending'||!id)return;const timer=setInterval(()=>{void authedFetch<Creation>(`/api/muse/jobs/${id}`).then(setValue).catch(()=>null);},5000);return()=>clearInterval(timer);} // eslint-disable-next-line react-hooks/exhaustive-deps
,[id,status]);}
export default function MuseCreate({initialStock}:{initialStock?:string}){
   const account=useAccountState();const [stock,setStock]=useState(initialStock||'AAPL');const [snapshot,setSnapshot]=useState<Snapshot|null>(null);const [capsule,setCapsule]=useState('');const [moment,setMoment]=useState('');const [lane,setLane]=useState<'news'|'nostalgia'|'agent'|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [creation,setCreation]=useState<Creation|null>(null);const [bannerCreation,setBannerCreation]=useState<Creation|null>(null);const seedRef=useRef('');const [adding,setAdding]=useState(false);const [name,setName]=useState('');const [refs,setRefs]=useState<string[]>([]);const [rights,setRights]=useState(false);const [asset,setAsset]=useState('USDC');const [paymentStatus,setPaymentStatus]=useState('');const [recoverable,setRecoverable]=useState(false);const [pulls,setPulls]=useState<Pulls|null>(null);
 const refresh=useCallback(async()=>{if(!account.authenticated)return;try{const value=await authedFetch<Snapshot>('/api/muse/snapshot');setSnapshot(value);setCapsule(old=>value.capsules.some(c=>c.id===old)?old:value.capsules.find(c=>c.status==='ready')?.id||'');setError('');}catch(e){setError(e instanceof Error?e.message:'Creation is unavailable');}try{setPulls(await authedFetch<Pulls>('/api/muse/pulls'));}catch{setPulls(null);}},[account.authenticated]);
 const news=useQuery({queryKey:['news-feed'],queryFn:async({signal})=>{const r=await fetch('/api/news/feed',{signal});const d=await r.json();if(!r.ok)throw new Error('news');return d as {items:{ticker:string;title:string;source:string}[]};},staleTime:5*60_000,retry:1});
 useEffect(()=>{const p=new URLSearchParams(location.search);const ticker=initialStock||p.get('stock');if(TOKENS.some(t=>t.ticker===ticker))setStock(ticker!);const m=p.get('moment');if(m)setMoment(m.slice(0,800));},[initialStock]);
 useEffect(()=>{setRecoverable(Boolean(sessionStorage.getItem(`daybreak-muse-payment:${account.user?.id}`)));void refresh();},[refresh,account.user?.id]);
 useEffect(()=>{if(!snapshot?.capsules.some(c=>c.status==='calibrating'))return;const id=setInterval(()=>void refresh(),8000);return()=>clearInterval(id);},[snapshot,refresh]);
  useCreationPoll(creation,setCreation);useCreationPoll(bannerCreation,setBannerCreation);
 const selected=snapshot?.capsules.find(c=>c.id===capsule);const price=snapshot?.config.prices.forge;
 async function pay(kind:'forge'|'create',id:string,input:unknown){
  setPaymentStatus('Preparing your fee…');
  const quote=await authedFetch<{to:string;value:string;data:string;amountRaw:string;recipient:string;chainId:number}>('/api/muse/quote',{method:'POST',body:JSON.stringify({id,kind,asset,capsuleId:kind==='forge'?capsule:undefined,input})});
  if(quote.chainId!==8453||quote.recipient.toLowerCase()!==snapshot?.payments.recipient.toLowerCase())throw new Error('Payment details changed. Refresh before paying.');
  if(quote.amountRaw==='0')return undefined;
  setPaymentStatus('Confirm the fee in your wallet');
  const txHash=await account.payCreationTransfer({to:quote.to,value:quote.value,data:quote.data});
  sessionStorage.setItem(`daybreak-muse-payment:${account.user?.id}`,JSON.stringify({id,kind,input,capsuleId:kind==='forge'?capsule:undefined,stock,txHash}));
  setRecoverable(true);setPaymentStatus('Confirming your payment…');
  await paymentClient.waitForTransactionReceipt({hash:txHash as Hex,confirmations:3,timeout:120000});
  return txHash;
 }
  async function askAgent(){if(!account.authenticated){account.login();return;}setBusy(true);setError('');try{const r=await authedFetch<{moment:string;cached:boolean}>('/api/muse/moment',{method:'POST',body:JSON.stringify({ticker:stock})});setMoment(r.moment);setLane('agent');}catch(e){setError(e instanceof Error?e.message:'Muse could not write a moment');}finally{setBusy(false);}}
  async function loadPull(p:PullItem){setBusy(true);setError('');try{const full=await authedFetch<Creation>(`/api/muse/jobs/${p.id}`);if(typeof full.moment_text==='string'&&full.moment_text){setMoment(full.moment_text);seedRef.current=full.moment_text;}if(full.moment_lane==='news'||full.moment_lane==='nostalgia'||full.moment_lane==='agent')setLane(full.moment_lane);else setLane(null);if(full.kind==='banner')setBannerCreation(full);else setCreation(full);}catch(e){setError(e instanceof Error?e.message:'Could not load that pull');}finally{setBusy(false);}}
  function saveSession(payload:object){try{sessionStorage.setItem(`daybreak-muse-payment:${account.user?.id}`,JSON.stringify(payload));}catch{}}
  async function generate(ckind:'pfp'|'banner'){if(!account.authenticated){account.login();return;}if(ckind==='banner'&&creation?.status!=='completed')return;setBusy(true);setError('');const isBanner=ckind==='banner';const id=crypto.randomUUID();const company=TOKENS.find(t=>t.ticker===stock)?.name??stock;const seed=seedRef.current||moment.trim();const input=isBanner?{moment:bannerArt(company,seed||`Epic wide art for the ${stock} community.`)}:{moment:pfpArt(company,moment.trim()||`${stock} community avatar.`)};const pullGroup=isBanner&&creation?creation.id:null;const postForge=(tx?:string,free?:boolean)=>authedFetch<Creation>('/api/muse/forge',{method:'POST',body:JSON.stringify({id,capsuleId:capsule,ticker:stock,moment:input.moment,kind:ckind,pullGroup,lane,txHash:tx,freePull:free===true})});const setResult=(r:Creation)=>{if(isBanner)setBannerCreation(r);else{setCreation(r);seedRef.current=input.moment;}};const busyMsg=isBanner?'Forging your banner…':'Forging your PFP…';try{const attemptFree=!isBanner&&(pulls?.freeLeft??0)>0;let result:Creation;if(attemptFree){setPaymentStatus('Using your free daily pull…');saveSession({id,kind:'forge',input,capsuleId:capsule,stock,ckind,pullGroup,lane});setCreation({id,status:'pending'});try{result=await postForge(undefined,true);}catch{const txHash=await pay('forge',id,input);saveSession({id,kind:'forge',input,capsuleId:capsule,stock,txHash,ckind,pullGroup,lane});setPaymentStatus(busyMsg);result=await postForge(txHash,false);}}else{const txHash=await pay('forge',id,input);saveSession({id,kind:'forge',input,capsuleId:capsule,stock,txHash,ckind,pullGroup,lane});setPaymentStatus(busyMsg);if(isBanner)setBannerCreation({id,status:'pending'});else setCreation({id,status:'pending'});result=await postForge(txHash,false);}setResult(result);if(result.status==='completed')sessionStorage.removeItem(`daybreak-muse-payment:${account.user?.id}`);void refresh();}catch(e){setError(e instanceof Error?e.message:'Creation could not finish');try{const fallback=await authedFetch<Creation>(`/api/muse/jobs/${id}`);setResult(fallback);}catch{if(isBanner)setBannerCreation(null);else setCreation(null);}}finally{setBusy(false);setPaymentStatus('');}}
 async function addReferences(files:FileList|null){if(!files)return;setError('');try{const chosen=Array.from(files).slice(0,4);if(chosen.some(f=>!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>1_300_000))throw new Error('Choose JPG, PNG or WebP references under 1.3 MB each.');const values=await Promise.all(chosen.map(f=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(f);})));setRefs(values);}catch(e){setError(e instanceof Error?e.message:'Could not read references');}}
 async function createCapsule(){setBusy(true);setError('');const id=crypto.randomUUID();const input={name,statement:`A visual world for the ${stock} community.`,references:refs,rightsConfirmed:rights};try{const txHash=await pay('create',id,input);await authedFetch('/api/muse/capsules',{method:'POST',body:JSON.stringify({requestId:id,input,txHash})});sessionStorage.removeItem(`daybreak-muse-payment:${account.user?.id}`);setAdding(false);setRefs([]);void refresh();}catch(e){setError(e instanceof Error?e.message:'Could not create the visual world');}finally{setBusy(false);setPaymentStatus('');}}
  async function recover(){const raw=sessionStorage.getItem(`daybreak-muse-payment:${account.user?.id}`);if(!raw)return;setBusy(true);setError('');try{const saved=JSON.parse(raw);setPaymentStatus('Checking your paid request…');if(saved.txHash)await paymentClient.waitForTransactionReceipt({hash:saved.txHash,confirmations:3,timeout:120000});if(saved.kind==='forge'){const ckind=saved.ckind==='banner'?'banner':'pfp';const replayFree=!saved.txHash&&ckind!=='banner';const done=await authedFetch<Creation>('/api/muse/forge',{method:'POST',body:JSON.stringify({id:saved.id,capsuleId:saved.capsuleId,ticker:saved.stock,moment:saved.input.moment,kind:ckind,pullGroup:saved.pullGroup??null,lane:saved.lane??null,txHash:saved.txHash,freePull:replayFree})});if(ckind==='banner')setBannerCreation(done);else setCreation(done);}else{await authedFetch('/api/muse/capsules',{method:'POST',body:JSON.stringify({requestId:saved.id,input:saved.input,txHash:saved.txHash})});}void refresh();}catch(e){setError(e instanceof Error?e.message:'Could not recover your request');}finally{setBusy(false);setPaymentStatus('');}}
  async function useArtwork(id:string){setBusy(true);try{await authedFetch('/api/muse/publish',{method:'POST',body:JSON.stringify({id})});location.assign(`/app/launch?stock=${stock}&creation=${id}`);}catch(e){setError(e instanceof Error?e.message:'Could not use artwork');setBusy(false);}}
 return <section className="db-create"><header className="db-create-heading"><div><span className="db-eyebrow">Made with Muse</span><h2>Make a meme<br/>worth sharing.</h2><p>Pick a stock, describe the moment, and we generate the image.</p></div>{account.authenticated&&snapshot&&<label className="db-create-currency">Pay with<select value={asset} onChange={e=>setAsset(e.target.value)}>{snapshot.payments.assets.map(a=><option value={a.symbol} key={a.symbol}>{a.label}</option>)}</select></label>}</header>
 <div className="db-create-layout"><div className="db-create-composer"><div className="db-create-stock"><StockIcon ticker={stock} size={40}/><label>Creating for<select value={stock} onChange={e=>setStock(e.target.value)}>{TOKENS.map(t=><option key={t.ticker}>{t.ticker}</option>)}</select></label></div>
 {!account.authenticated?<div className="db-create-welcome"><Sparkles size={26}/><h3>Your idea belongs here.</h3><p>Sign in to Daybreak to choose a visual world and create. Everything happens here.</p><button className="db-button db-blue-button" onClick={()=>account.login()}>Sign in to create <ArrowRight size={16}/></button></div>:<>
 <div className="db-create-label"><h3>Choose a visual world</h3><button className="db-text-link" onClick={()=>setAdding(!adding)}><Plus size={15}/> New</button></div>
 <div className="db-create-capsules">{snapshot?.capsules.map(c=><button key={c.id} type="button" aria-pressed={capsule===c.id} disabled={c.status!=='ready'} onClick={()=>setCapsule(c.id)} style={{'--capsule-accent':c.accent} as React.CSSProperties}><span className="db-create-capsule-art">{c.cover?<img src={c.cover} alt=""/>:<Sparkles size={27}/>}</span><strong>{c.name}</strong><small>{c.status==='calibrating'?'Preparing your world…':c.status==='ready'?'Ready to create':c.status}</small></button>)}</div>
 {snapshot&&!snapshot.capsules.length&&<p className="db-small-note">Create the first visual world with a few reference images.</p>}
 {adding&&<div className="db-create-new"><label>World name<input value={name} maxLength={48} onChange={e=>setName(e.target.value)} placeholder="Your community’s visual world"/></label><label className="db-create-upload"><ImagePlus size={20}/> Add 2–4 reference images<input type="file" accept="image/png,image/jpeg,image/webp" multiple onChange={e=>void addReferences(e.target.files)}/></label><div className="db-create-reference-row">{refs.map((src,i)=><img key={i} src={src} alt={`Reference ${i+1}`}/>)}</div><label className="db-create-consent"><input type="checkbox" checked={rights} onChange={e=>setRights(e.target.checked)}/> I own or have permission to use these references. This world will be shared for community creation.</label><button className="db-button db-blue-button" disabled={busy||!rights||refs.length<2||name.trim().length<2||!snapshot?.config.enabled||!snapshot?.payments.enabled} onClick={()=>void createCapsule()}>Create world · ${snapshot?.config.prices.create.toFixed(2)??'—'} · {asset}</button></div>}
  {(()=>{const picks=news.data?.items??[];const forStock=picks.filter(i=>i.ticker===stock).slice(0,4);const list=forStock.length?forStock:picks.slice(0,4);return list.length>0?<div className="db-create-news"><span className="db-eyebrow">Meme a news moment</span><div className="db-create-news-row">{list.map((n,i)=><button type="button" key={n.title+i} onClick={()=>{if(n.ticker!==stock&&TOKENS.some(t=>t.ticker===n.ticker))setStock(n.ticker);setLane('news');setMoment(memeMoment(n.title,TOKENS.find(t=>t.ticker===n.ticker)?.name??n.ticker));}}><strong>{n.ticker}</strong><span>{n.title}</span></button>)}</div></div>:null;})()}
  <div className="db-create-news"><span className="db-eyebrow">Blast from the past · {stock} lore</span>{(()=>{const past=momentsFor(stock);return past.length?<div className="db-create-news-row">{past.map(n=><button type="button" key={n.title} onClick={()=>{setLane('nostalgia');setMoment(nostalgiaMoment(n));}}><strong>{n.title}</strong><span>{n.blurb}</span></button>)}</div>:<p className="db-small-note">No past moments filed for {stock} yet — type one above or pull from the news.</p>;})()}</div>
  <label className="db-create-moment">What’s the moment?<button type="button" className="db-text-link" disabled={busy} onClick={()=>void askAgent()}>Muse writes one</button><textarea value={moment} maxLength={800} onChange={e=>{setMoment(e.target.value);setLane(null);}} placeholder={`A tiny astronaut watching ${stock} rise over the horizon…`}/></label>
  {lane==='agent'&&<p className="db-small-note">AI-written — review it before you pull.</p>}
  <button className="db-button db-blue-button db-create-generate" disabled={busy||creation?.status==='pending'||!selected||!snapshot?.config.enabled||!snapshot?.payments.enabled} onClick={()=>void generate('pfp')}>{busy||creation?.status==='pending'?<><LoaderCircle size={17} className="db-spin"/> {paymentStatus||'Pulling your moment…'}</>:(pulls?.freeLeft??0)>0?<><Sparkles size={17}/> Free pull · 1 today</>:<><Sparkles size={17}/> Pull the PFP · ${price?.toFixed(2)??'—'} · {asset}</>}</button><p className="db-small-note">Every pull is a fresh roll — the same moment never lands twice.{(pulls?.freeLeft??0)>0?' Your first pull today is free; extra pulls are paid.':' Pay the creation fee directly on Base.'} If generation fails, the fee becomes retry balance; no second payment is needed.</p>

 </>}{recoverable&&<button className="db-text-link" disabled={busy} onClick={()=>void recover()}>Check paid request · no new payment</button>}{error&&<p role="alert" className="db-launch-error">{error}</p>}</div>
   <aside className="db-create-output" aria-live="polite">{creation?.image?<><img className="db-create-finished" src={creation.image} alt={`Community artwork created for ${stock}`}/><div className="db-create-result"><strong><Check size={16}/> Nice pull — yours to share.</strong><p>{creation.eligible?'+1 Spotlight point for this stock community.':'Saved. This creation does not earn a paid Spotlight point.'}</p><a className="db-button" href={creation.image} download={`daybreak-${stock}-${creation.id}.webp`}><Download size={16}/> Download</a><button className="db-button db-blue-button" disabled={busy} onClick={()=>creation&&void useArtwork(creation.id)}>Use as token artwork <ArrowRight size={16}/></button><small>Using this artwork for a token publishes the image.</small></div>{bannerCreation?.image?<><img className="db-create-finished" src={bannerCreation.image} alt={`Banner artwork for the ${stock} community token`}/><div className="db-create-result"><strong><Check size={16}/> Banner forged.</strong><p>Same moment, cut wide for the token page.</p><a className="db-button" href={bannerCreation.image} download={`daybreak-${stock}-${bannerCreation.id}-banner.webp`}><Download size={16}/> Download</a></div></>:bannerCreation?.status==='pending'?<p className="db-small-note">Forging your banner… you can stay here.</p>:<><button className="db-button db-blue-button" disabled={busy||!selected||!snapshot?.config.enabled||!snapshot?.payments.enabled} onClick={()=>void generate('banner')}>{busy?<><LoaderCircle size={17} className="db-spin"/> Forging…</>:<>Forge the banner · ${price?.toFixed(2)??'—'} · {asset}</>}</button><p className="db-small-note">Second pull from the same moment seed. Paid forge, like the first.</p></>}</>:<div className="db-create-placeholder"><div className="db-create-orbit"><Sparkles size={44}/><StockIcon ticker={stock} size={48}/></div><h3>{creation?.status==='pending'?'Your idea is taking shape.':'A little imagination goes a long way.'}</h3><p>{creation?.status==='pending'?'You can stay here while Muse creates. Your request is saved.':selected?.statement||'Choose a world, describe a moment, and make it yours.'}</p>{creation?.status==='failed'&&<p role="alert">{creation.error}</p>}</div>}</aside></div>
  <Link href="/app" className="db-text-link">Back to stocks <ArrowRight size={16}/></Link>
  {pulls&&pulls.pulls.length>0&&<div className="db-create-news"><span className="db-eyebrow">Your pulls</span><div className="db-create-news-row">{pulls.pulls.map(p=><button type="button" key={p.id} disabled={p.status!=='completed'||!p.has_image} onClick={()=>void loadPull(p)}><strong>{p.kind==='banner'?'Banner':(p.ticker??'Pull')}</strong><span>{p.status==='completed'?(p.kind==='banner'?'banner · tap to reopen':'tap to reopen'):'still forging…'}</span></button>)}</div></div>}
  {pulls&&pulls.community.length>0&&<div className="db-create-news"><span className="db-eyebrow">Community pulls</span><div className="db-create-news-row">{pulls.community.map(c=><span key={c.id} className="db-create-community-pull"><img src={c.image} alt={`${c.ticker} community pull`} loading="lazy"/><strong>{c.ticker}</strong></span>)}</div></div>}</section>;
}
