'use client';
import { useCallback, useEffect, useMemo, useState, useRef } from 'react';
import { ArrowLeft, ArrowRight, Beaker, LoaderCircle, Plus, Share2, ShieldCheck, Users } from 'lucide-react';
import Link from 'next/link';
import { authedFetch } from '@/lib/account/api-client';
import { PAPER_FEE_BPS, quotePaperTrade, type PaperDirection, type PaperQuote, type PaperTradeIntent } from '@/lib/theses/paper';
import { ProfileAvatar, StockIcon } from '../Identity';
import { useAccountState } from '../AccountProvider';
import type { PublicPaperMarketView, ThesisInstrumentView, ThesisView } from './types';

const format=(value:number,digits=4)=>new Intl.NumberFormat(undefined,{maximumFractionDigits:digits}).format(value);
const signed=(value:number,symbol:string)=>`${value>=0?'+':'−'}${format(Math.abs(value))} ${symbol}`;

export default function PaperTradingMode({instruments,instrumentState,initialThesis,onClose,onPublished}:{instruments:ThesisInstrumentView[];instrumentState:'loading'|'ready'|'error';initialThesis?:ThesisView|null;onClose:()=>void;onPublished?:(thesis:ThesisView)=>void}){
  const account=useAccountState();
  const [pages,setPages]=useState({positions:0,trades:0,balances:0});
  const [intent,setIntent]=useState<PaperTradeIntent|null>(null);
  const [pending,setPending]=useState(false);
  const [receipt,setReceipt]=useState('');
  const generation=useRef(0);

  const available=useMemo(()=>instruments.filter(item=>item.lifecycle.create),[instruments]);
  const [active,setActive]=useState<ThesisView|null>(initialThesis??null);
  const [screen,setScreen]=useState<'create'|'market'>(initialThesis?'market':'create');
  const [market,setMarket]=useState<PublicPaperMarketView|null>(null);
  const [marketState,setMarketState]=useState<'idle'|'loading'|'ready'|'error'>('idle');
  const [direction,setDirection]=useState<PaperDirection>('buy'); const [amount,setAmount]=useState('');
  const [quote,setQuote]=useState<PaperQuote|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  const [draft,setDraft]=useState({instrumentId:'',title:'',summary:'',tokenName:'',tokenSymbol:''});
  const draftInstrument=available.find(item=>item.id===draft.instrumentId)??available[0];
  const instrument=available.find(item=>item.id===active?.instrumentId);

  useEffect(()=>{if(!available.length)return;setDraft(current=>{const selected=available.find(item=>item.id===current.instrumentId)??available[0];return {...current,instrumentId:selected.id,tokenName:current.tokenName||`${selected.companyName} Thesis`,tokenSymbol:current.tokenSymbol||`${selected.ticker}IDEA`}})},[available]);
  useEffect(()=>{if(initialThesis){setActive(initialThesis);setScreen('market')}},[initialThesis]);
  const loadMarket=useCallback(async()=>{if(!active)return;const version=++generation.current;const pageQuery=`positionsPage=${pages.positions}&tradesPage=${pages.trades}&balancesPage=${pages.balances}`;setMarketState(current=>current==='ready'?'ready':'loading');try{const result=account.authenticated?await authedFetch<{market:PublicPaperMarketView}>(`/api/theses/paper/${active.id}?viewer=1&${pageQuery}`):await fetch(`/api/theses/paper/${active.id}?${pageQuery}`,{cache:'no-store'}).then(async response=>{if(!response.ok)throw Error('Paper market unavailable');return response.json()});if(version!==generation.current)return;setMarket(result.market);setMarketState('ready')}catch{if(version===generation.current)setMarketState('error')}},[active,account.authenticated,account.user?.id,pages]);
  useEffect(()=>{if(screen!=='market'||!active)return;void loadMarket();const timer=setInterval(()=>void loadMarket(),8_000);return()=>{clearInterval(timer);generation.current++}},[screen,active,loadMarket]);
  useEffect(()=>{setQuote(null);setIntent(null);setAmount('');setError('')},[direction,active?.id]);
  useEffect(()=>{setMarket(null);setQuote(null);setIntent(null);setPending(false);setReceipt('')},[account.user?.id]);

  const updateInstrument=(instrumentId:string)=>{const selected=available.find(item=>item.id===instrumentId);setDraft(current=>({...current,instrumentId,tokenName:`${selected?.companyName??''} Thesis`,tokenSymbol:`${selected?.ticker??''}IDEA`}))};
  const create=async()=>{if(!draftInstrument)return;if(!account.authenticated){account.login();return}setBusy(true);setError('');try{const result=await authedFetch<{thesis:ThesisView}>('/api/theses/paper',{method:'POST',body:JSON.stringify(draft)});setActive(result.thesis);setScreen('market');setDraft(current=>({...current,title:'',summary:''}));onPublished?.(result.thesis)}catch(caught){setError(caught instanceof Error?caught.message:'Paper thesis could not be published')}finally{setBusy(false)}};
  const preview=()=>{if(!market||!instrument)return;setError('');try{const input=Number(amount);const viewer=market.viewer;if(direction==='buy'&&viewer&&input>viewer.stockBalance)throw Error('Not enough paper stock tokens');if(direction==='sell'&&input>(viewer?.position?.quantity??0))throw Error('Not enough paper thesis tokens');const next=quotePaperTrade(market,direction,input);setQuote(next);setIntent({intentId:crypto.randomUUID(),minimumOutput:next.outputAmount*0.99,expiresAt:Date.now()+60_000});setReceipt('')}catch(caught){setQuote(null);setError(caught instanceof Error?caught.message:'Paper quote unavailable')}};
  const execute=async()=>{if(!active||!quote||!intent||busy)return;if(!account.authenticated){account.login();return}setBusy(true);setPending(true);setError('');try{const result=await authedFetch<{receipt:{id:string;outputAmount:number}}>(`/api/theses/paper/${active.id}/trade`,{method:'POST',body:JSON.stringify({direction,amount:quote.inputAmount,...intent})});setReceipt(`Trade confirmed · received ${format(result.receipt.outputAmount)} ${direction==='buy'?active.tokenSymbol:instrument?.symbol}`);setPending(false);setQuote(null);setIntent(null);setAmount('');await loadMarket()}catch(caught){const status=(caught as {status?:number}).status;if(status&&[400,404,409].includes(status)){setPending(false);setQuote(null);setIntent(null)}setError(caught instanceof Error?caught.message:'Connection interrupted. Retry the same trade safely.')}finally{setBusy(false)}};
  const share=async()=>{if(!active)return;const url=`${location.origin}/theses/${active.slug}`;if(navigator.share)await navigator.share({title:active.title,text:active.summary,url}).catch(()=>{});else await navigator.clipboard.writeText(url)};

  if(!available.length)return <section className="db-paper-mode"><button className="db-text-link" onClick={onClose}><ArrowLeft size={15}/> Conviction</button>{instrumentState==='loading'?<div className="db-thesis-loading"><LoaderCircle className="db-spin" size={20}/> Preparing paper markets…</div>:<div className="db-thesis-empty"><Beaker size={26}/><h3>Paper markets are unavailable.</h3><p>The supported stock-token list could not be loaded.</p></div>}</section>;

  if(screen==='create'||!active||!instrument)return <section className="db-paper-mode">
    <div className="db-paper-top"><button className="db-text-link" onClick={active?()=>setScreen('market'):onClose}><ArrowLeft size={15}/> {active?'Paper market':'Conviction'}</button><span className="db-paper-badge"><Users size={14}/> Public simulation</span></div>
    <div className="db-paper-create"><header><span className="db-eyebrow">Publish a paper thesis</span><h2>Start with an idea.</h2><p>Simplified practice model: fixed 2% input fee, constant-product curve, no graduation. Live uses Meteora’s scheduled and dynamic fees, quote-token fee collection and graduation.</p><p>Your thesis, market activity, participant positions and paper P/L will be public. No wallet, signature or real stock token is used.</p></header><div className="db-paper-create-grid"><div className="db-thesis-fields">
      <label>Paired stock token<select value={draft.instrumentId||draftInstrument.id} onChange={event=>updateInstrument(event.target.value)}>{available.map(item=><option key={item.id} value={item.id}>{item.companyName} · {item.symbol}</option>)}</select></label>
      <label>Thesis title<input value={draft.title} maxLength={100} onChange={event=>setDraft(current=>({...current,title:event.target.value}))} placeholder="Apple services will drive its next growth cycle"/></label>
      <label>Why you believe it<textarea value={draft.summary} maxLength={280} onChange={event=>setDraft(current=>({...current,summary:event.target.value}))} placeholder="Write the specific case people will assess before joining the simulation."/></label>
      <div className="db-thesis-field-pair"><label>Paper token name<input value={draft.tokenName} maxLength={32} onChange={event=>setDraft(current=>({...current,tokenName:event.target.value}))}/></label><label>Symbol<input value={draft.tokenSymbol} maxLength={10} onChange={event=>setDraft(current=>({...current,tokenSymbol:event.target.value.toUpperCase().replace(/[^A-Z0-9]/g,'')}))}/></label></div>
      {error&&<p className="db-thesis-error" role="alert">{error}</p>}<button className="db-button db-blue-button" disabled={busy} onClick={create}>{busy?<LoaderCircle className="db-spin" size={16}/>:<Beaker size={16}/>} {account.authenticated?'Publish paper thesis':'Sign in to publish'}</button>
    </div><aside className="db-paper-create-review"><StockIcon ticker={draftInstrument.ticker} size={48}/><span className="db-paper-badge">Public paper pair</span><h3>{draft.title||'Your thesis title'}</h3><p>{draft.summary||'Your reasoning will appear in Conviction for everyone to discover.'}</p><dl><div><dt>Pair</dt><dd>{draft.tokenSymbol||`${draftInstrument.ticker}IDEA`} / {draftInstrument.symbol}</dd></div><div><dt>Starting allocation</dt><dd>10 {draftInstrument.symbol} each</dd></div><div><dt>Market and P/L</dt><dd>Public</dd></div><div><dt>Wallet signature</dt><dd>None</dd></div></dl></aside></div></div>
  </section>;

  const viewerPosition=market?.viewer?.position; const positions=market?.positions??[]; const trades=market?.trades??[];
  return <section className="db-paper-mode">
    <div className="db-paper-top"><button className="db-text-link" onClick={onClose}><ArrowLeft size={15}/> Conviction</button><div><button className="db-text-link" onClick={()=>setScreen('create')}><Plus size={14}/> New paper thesis</button><button className="db-text-link" onClick={share}><Share2 size={14}/> Share</button></div></div>
    <header className="db-paper-head"><div><span className="db-paper-badge"><Users size={14}/> Public paper market</span><h2>{active.title}</h2><p>{active.summary}</p></div><div className="db-paper-live-stat"><span>Public activity</span><strong>{market?.tradeCount??0} trades</strong><small>{positions.length} positions on this page</small></div></header>
    {marketState==='loading'?<div className="db-thesis-loading"><LoaderCircle className="db-spin" size={20}/> Loading the shared paper market…</div>:marketState==='error'||!market?<div className="db-thesis-empty"><ShieldCheck size={26}/><h3>Paper market unavailable.</h3><button className="db-button" onClick={()=>void loadMarket()}>Try again</button></div>:<>
      <div className="db-paper-summary"><div><span>Your paper stock balance</span><strong>{market.viewer?`${format(market.viewer.stockBalance)} ${instrument.symbol}`:'Sign in to participate'}</strong><small>Public after your first trade</small></div><div><span>Your thesis position</span><strong>{format(viewerPosition?.quantity??0,2)} {active.tokenSymbol}</strong><small>Worth {format(viewerPosition?.marketValueQuote??0)} {instrument.symbol}</small></div><div><span>Your mark-to-market P/L</span><strong className={(viewerPosition?.totalPnlQuote??0)>=0?'is-positive':'is-negative'}>{signed(viewerPosition?.totalPnlQuote??0,instrument.symbol)}</strong><small>Estimated exit P/L: {signed(viewerPosition?.estimatedExitPnl??0,instrument.symbol)}</small></div></div>
      <div className="db-paper-grid"><article className="db-paper-market"><div className="db-thesis-company"><StockIcon ticker={instrument.ticker} size={46}/><div><strong>{active.tokenSymbol} / {instrument.symbol}</strong><span>One shared curve · everyone moves the same market</span></div><span className="db-paper-badge">Live simulation</span></div><div className="db-paper-price"><span>Public thesis price</span><strong>{format(market.spotPrice,6)} {instrument.symbol}</strong><small>Every public Back or Sell changes this price for the next participant.</small></div><div className="db-thesis-trade-tabs"><button aria-pressed={direction==='buy'} disabled={pending||busy} onClick={()=>setDirection('buy')}>Back</button><button aria-pressed={direction==='sell'} disabled={pending||busy} onClick={()=>setDirection('sell')}>Sell</button></div><label className="db-thesis-amount"><span>You {direction==='buy'?'spend':'sell'}</span><div><input disabled={pending||busy} inputMode="decimal" value={amount} onChange={event=>{setAmount(event.target.value);setQuote(null);setError('')}} placeholder="0.00" aria-label={`Paper amount in ${direction==='buy'?instrument.symbol:active.tokenSymbol}`}/><strong>{direction==='buy'?instrument.symbol:active.tokenSymbol}</strong></div></label>{quote?<div className="db-thesis-quote-review"><dl><div><dt>You receive</dt><dd>{format(quote.outputAmount)} {direction==='buy'?active.tokenSymbol:instrument.symbol}</dd></div><div><dt>Paper fee</dt><dd>{format(quote.feeAmount)}</dd></div><div><dt>Price impact</dt><dd>{format(quote.priceImpactPct,2)}%</dd></div><div><dt>Minimum received (1% slippage)</dt><dd>{format(intent?.minimumOutput??0)}</dd></div><div><dt>Preview valid</dt><dd>60 seconds</dd></div><div><dt>Visibility</dt><dd>Public</dd></div></dl><button className="db-button db-blue-button" disabled={busy} onClick={execute}>{busy?<LoaderCircle className="db-spin" size={16}/>:<Beaker size={16}/>} {pending?'Retry same trade':account.authenticated?'Execute public paper trade':'Sign in to trade'}</button></div>:<button className="db-button db-blue-button" disabled={!amount} onClick={preview}><ArrowRight size={16}/> Preview paper trade</button>}{receipt&&<p role="status">{receipt}</p>}{error&&<p className="db-thesis-error" role="alert">{error}</p>}<p>Simplified practice: constant-product curve, fixed 2% input fee, no graduation. Live uses scheduled and dynamic Meteora fees collected in the quote token, and graduation. Mark-to-market P/L is not an exit quote; estimated exit includes current impact and fees.</p><p className="db-paper-disclosure"><ShieldCheck size={15}/> This is a shared public simulation. Your position, paper balance, activity and P/L are visible to everyone. No wallet, signature or real asset moves.</p></article>
      <aside className="db-paper-learn db-paper-leaderboard"><span className="db-eyebrow">Public positions and balances</span><h3>Conviction leaderboard</h3><p>Ranked by tokens held · mark-to-market P/L</p>{positions.length?<div>{positions.map((position,index)=><article key={position.publicId}><span>{pages.positions*50+index+1}</span><ProfileAvatar imageUrl={position.avatarUrl} seed={position.avatar??0} size={30}/><div><Link href={`/paper/participants/${position.publicId}`}>{position.displayName||'Daybreak member'} · {position.publicId.slice(0,6)}{position.isViewer?' · You':''}</Link><small>{format(position.quantity,2)} {active.tokenSymbol} · {format(position.stockBalance??0)} {instrument.symbol} left</small></div><b className={position.totalPnlQuote>=0?'is-positive':'is-negative'}>{signed(position.totalPnlQuote,instrument.symbol)}</b></article>)}</div>:<p>Be the first public position in this thesis.</p>}<nav aria-label="Position pages">{pages.positions>0&&<button className="db-button" onClick={()=>setPages(p=>({...p,positions:p.positions-1}))}>Previous</button>}{market.hasMore.positions&&<button className="db-button" onClick={()=>setPages(p=>({...p,positions:p.positions+1}))}>Next positions</button>}</nav></aside></div>
      <section className="db-paper-ledger"><div><span className="db-eyebrow">Public activity</span><h3>Everyone trading {active.tokenSymbol}</h3></div>{trades.length?<div>{trades.map(trade=><article key={trade.id}><span className={trade.direction==='buy'?'is-buy':'is-sell'}>{trade.direction==='buy'?'Backed':'Sold'}</span><Link href={`/paper/participants/${trade.publicId}`}>{trade.displayName||'Daybreak member'} · {trade.publicId.slice(0,6)}{trade.isViewer?' · You':''}</Link><span>{format(trade.inputAmount)} {trade.direction==='buy'?instrument.symbol:active.tokenSymbol} → {format(trade.outputAmount)} {trade.direction==='buy'?active.tokenSymbol:instrument.symbol}</span><time>{new Date(trade.executedAt).toLocaleString()}</time></article>)}</div>:<p>No public trades yet. Be the first to move the paper curve.</p>}<nav aria-label="Activity pages">{pages.trades>0&&<button className="db-button" onClick={()=>setPages(p=>({...p,trades:p.trades-1}))}>Previous</button>}{market.hasMore.trades&&<button className="db-button" onClick={()=>setPages(p=>({...p,trades:p.trades+1}))}>Older trades</button>}</nav></section>
      <section className="db-paper-ledger"><h3>Public {instrument.symbol} balances</h3>{market.balances.map(b=><article key={b.publicId}><Link href={`/paper/participants/${b.publicId}`}>{b.displayName||'Daybreak member'} · {b.publicId.slice(0,6)}</Link><span>{format(b.balance)} {instrument.symbol}</span></article>)}<nav>{pages.balances>0&&<button className="db-button" onClick={()=>setPages(p=>({...p,balances:p.balances-1}))}>Previous</button>}{market.hasMore.balances&&<button className="db-button" onClick={()=>setPages(p=>({...p,balances:p.balances+1}))}>Next balances</button>}</nav></section>
    </>}
  </section>;
}
