'use client';
import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, BookOpenText, LoaderCircle, Plus, Search, ShieldCheck } from 'lucide-react';
import ThesisCard from './ThesisCard';
import ThesisComposer from './ThesisComposer';
import ThesisDetail from './ThesisDetail';
import type { ThesisInstrumentView, ThesisView } from './types';

export default function ThesisHub() {
  const [instruments,setInstruments]=useState<ThesisInstrumentView[]>([]); const [items,setItems]=useState<ThesisView[]>([]);
  const [state,setState]=useState<'loading'|'ready'|'error'>('loading'); const [mode,setMode]=useState<'feed'|'create'|'detail'>('feed');
  const [active,setActive]=useState<ThesisView|null>(null); const [query,setQuery]=useState(''); const [tab,setTab]=useState<'explore'|'following'|'positions'>('explore');
  useEffect(()=>{const controller=new AbortController();Promise.all([fetch('/api/theses',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error();return r.json()}),fetch('/api/theses/instruments',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error();return r.json()})]).then(([theses,available])=>{setItems(theses.items||[]);setInstruments(available.items||[]);setState('ready');const requested=new URLSearchParams(location.search).get('thesis');const found=(theses.items||[]).find((item:ThesisView)=>item.id===requested||item.slug===requested);if(found){setActive(found);setMode('detail')}}).catch((error)=>{if(error?.name!=='AbortError')setState('error')});return()=>controller.abort()},[]);
  const filtered=useMemo(()=>{const needle=query.trim().toLowerCase();return needle?items.filter((item)=>[item.title,item.summary,item.companyId,item.tokenSymbol].some(value=>value.toLowerCase().includes(needle))):items},[items,query]);
  const instrumentFor=(thesis:ThesisView)=>instruments.find((instrument)=>instrument.id===thesis.instrumentId);
  if(mode==='create')return <ThesisComposer instruments={instruments} initialTicker={new URLSearchParams(typeof location==='undefined'?'':location.search).get('stock')||undefined} onClose={()=>setMode('feed')} onPublished={(slug)=>{location.href=`/theses/${slug}`}}/>;
  if(mode==='detail'&&active)return <ThesisDetail thesis={active} instrument={instrumentFor(active)} onBack={()=>{setActive(null);setMode('feed')}}/>;
  return <section className="db-thesis-hub">
    <header className="db-thesis-hub-head"><div><span className="db-eyebrow">Stock-paired thesis markets</span><h2>Ideas worth backing.</h2><p>Read the case. Inspect the exact stock-token pair. Back it only when the market is verified.</p></div><button className="db-button db-blue-button" onClick={()=>setMode('create')}><Plus size={17}/> Create a thesis</button></header>
    <div className="db-thesis-toolbar"><label><Search size={16}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search theses or companies" aria-label="Search theses or companies"/></label><div className="db-thesis-tabs">{([['explore','Explore'],['following','Following'],['positions','My positions']] as const).map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</div></div>
    {tab!=='explore'?<div className="db-thesis-empty"><BookOpenText size={26}/><h3>{tab==='following'?'No saved theses yet.':'No verified thesis positions yet.'}</h3><p>{tab==='following'?'Save a published thesis to keep its updates close.':'Positions appear after exact buy and sell validation opens for a market.'}</p><button className="db-text-link" onClick={()=>setTab('explore')}>Explore theses <ArrowRight size={15}/></button></div>:state==='loading'?<div className="db-thesis-loading"><LoaderCircle className="db-spin" size={20}/> Loading thesis markets…</div>:state==='error'?<div className="db-thesis-empty"><ShieldCheck size={26}/><h3>Thesis markets are unavailable.</h3><p>Your stocks and Circles are still available. Try this section again shortly.</p></div>:filtered.length?<div className="db-thesis-grid">{filtered.map((thesis)=><ThesisCard key={thesis.id} thesis={thesis} instrument={instrumentFor(thesis)} onOpen={()=>{setActive(thesis);setMode('detail')}}/>)}</div>:<div className="db-thesis-empty"><BookOpenText size={28}/><h3>{query?'No thesis matches that search.':'The first verified thesis starts here.'}</h3><p>{query?'Try a company name, ticker or idea.':'Publish a clear case, pair it directly with its stock token, and let people assess it.'}</p>{!query&&<button className="db-button db-blue-button" onClick={()=>setMode('create')}>Create the first thesis</button>}</div>}
    <aside className="db-thesis-method"><ShieldCheck size={18}/><div><strong>Exact pairs, visible terms.</strong><p>Every enabled market names its stock-token mint, fee schedule and lifecycle state. Unsupported instruments never fall back to USDC.</p></div></aside>
  </section>;
}
