import {ROOM_SIMULATIONS} from './fixtures/instruments';
import { DiscoveryObject } from './types';

export const DISCOVERY_CATALOG: DiscoveryObject[] = [
  {
    id: 'laptop',
    label: 'Minimalist Laptop',
    category: 'Personal Computing',
    iconName: 'Laptop',
    color: '#d4d8dd',
    secondaryColor: '#2b3036',
    geometryType: 'laptop',
    anchorSlot: 0, // Main desk center
    company: {
      id: 'apple',
      name: 'Apple Inc.',
      ticker: 'AAPL',
      sector: 'Consumer Electronics & Silicon',
      summary: 'Designs consumer technology, software operating systems, and custom ARM silicon architectures.',
      headquarters: 'Cupertino, California, USA',
      primarySourceUrl: 'https://investor.apple.com',
    },
    relationship: {
      id: 'rel_laptop_apple',
      objectId: 'laptop',
      companyId: 'apple',
      relationshipType: 'manufactured_by',
      claim: 'Engineered, assembled, and distributed by Apple Inc. featuring proprietary M-Series Apple Silicon.',
      explanation:
        'From custom unified memory architecture to macOS system integration, Apple controls the complete hardware and software stack.',
      primarySourceUrl: 'https://www.apple.com/newsroom',
      sourceName: 'Apple Official Newsroom & Investor Disclosures',
      checkedAt: '2026-09-05',
      status: 'verified',
    },
    instrument: ROOM_SIMULATIONS.laptop,
  },
  {
    id: 'controller',
    label: 'Haptic Controller',
    category: 'Gaming & Entertainment',
    iconName: 'Gamepad2',
    color: '#eaeef4',
    secondaryColor: '#1d273b',
    geometryType: 'controller',
    anchorSlot: 1, // Desk right
    company: {
      id: 'sony',
      name: 'Sony Group Corporation',
      ticker: 'SONY',
      sector: 'Games, Sensors & Entertainment',
      summary: 'Japanese multinational conglomerate leading interactive gaming, image sensors, and music publishing.',
      headquarters: 'Tokyo, Japan',
      primarySourceUrl: 'https://www.sony.com/en/SonyInfo/IR',
    },
    relationship: {
      id: 'rel_controller_sony',
      objectId: 'controller',
      companyId: 'sony',
      relationshipType: 'brand_owned_by',
      claim: 'DualSense haptic feedback and adaptive trigger technology developed and patented by Sony Interactive Entertainment.',
      explanation:
        'Sony’s Game & Network Services division designs PlayStation consoles, proprietary voice-coil actuators, and custom audio chips.',
      primarySourceUrl: 'https://www.sony.com/en/SonyInfo/IR/library/presen/er',
      sourceName: 'Sony Corporate IR Annual Report',
      checkedAt: '2026-09-05',
      status: 'verified',
    },
    instrument: ROOM_SIMULATIONS.controller,
  },
  {
    id: 'parcel',
    label: 'Delivery Parcel',
    category: 'E-Commerce & Cloud',
    iconName: 'Package',
    color: '#d6a36c',
    secondaryColor: '#232f3e',
    geometryType: 'parcel',
    anchorSlot: 2, // Low floor shelf
    company: {
      id: 'amazon',
      name: 'Amazon.com, Inc.',
      ticker: 'AMZN',
      sector: 'Commerce & Cloud Infrastructure',
      summary: 'Global leader in e-commerce fulfillment, autonomous robotic sortation, and cloud compute via AWS.',
      headquarters: 'Seattle, Washington, USA',
      primarySourceUrl: 'https://ir.aboutamazon.com',
    },
    relationship: {
      id: 'rel_parcel_amazon',
      objectId: 'parcel',
      companyId: 'amazon',
      relationshipType: 'service_operated_by',
      claim: 'Delivered via Amazon Operations network, sortation robotics, and AWS route-optimization algorithms.',
      explanation:
        'Amazon coordinates multi-modal logistics across air, road, and micro-fulfillment centers powered by AWS compute clusters.',
      primarySourceUrl: 'https://ir.aboutamazon.com/annual-reports',
      sourceName: 'Amazon.com Form 10-K & Logistics Overview',
      checkedAt: '2026-09-05',
      status: 'verified',
    },
    instrument: ROOM_SIMULATIONS.parcel,
  },
  {
    id: 'screen',
    label: 'Cinema Display',
    category: 'Streaming & Media',
    iconName: 'Tv',
    color: '#1a1f26',
    secondaryColor: '#e50914',
    geometryType: 'screen',
    anchorSlot: 3, // Wall display mount
    company: {
      id: 'netflix',
      name: 'Netflix, Inc.',
      ticker: 'NFLX',
      sector: 'Entertainment Streaming Services',
      summary: 'Pioneered subscription video streaming, original studio production, and global content delivery networks.',
      headquarters: 'Los Gatos, California, USA',
      primarySourceUrl: 'https://ir.netflix.net',
    },
    relationship: {
      id: 'rel_screen_netflix',
      objectId: 'screen',
      companyId: 'netflix',
      relationshipType: 'service_operated_by',
      claim: 'Content streamed via Netflix Open Connect Content Delivery Network and proprietary AV1/HEVC compression.',
      explanation:
        'Netflix deploys custom caching appliances directly inside regional ISPs worldwide to deliver low-latency 4K streams.',
      primarySourceUrl: 'https://openconnect.netflix.com',
      sourceName: 'Netflix Open Connect Architecture Disclosures',
      checkedAt: '2026-09-05',
      status: 'verified',
    },
    instrument: ROOM_SIMULATIONS.screen,
  },
  {
    id: 'chip',
    label: 'Semiconductor Unit',
    category: 'AI & Hardware',
    iconName: 'Cpu',
    color: '#76b900',
    secondaryColor: '#121815',
    geometryType: 'chip',
    anchorSlot: 4, // High shelf display
    company: {
      id: 'nvidia',
      name: 'NVIDIA Corporation',
      ticker: 'NVDA',
      sector: 'Accelerated Computing & Semiconductors',
      summary: 'Pioneer of GPU computing, deep learning accelerator chips, and high-speed network fabrics.',
      headquarters: 'Santa Clara, California, USA',
      primarySourceUrl: 'https://investor.nvidia.com',
    },
    relationship: {
      id: 'rel_chip_nvidia',
      objectId: 'chip',
      companyId: 'nvidia',
      relationshipType: 'component_supplied_by',
      claim: 'Microarchitecture engineered by NVIDIA; manufactured via TSMC 4N FinFET lithography.',
      explanation:
        'NVIDIA designs the Tensor Core architecture and CUDA runtime software, while Taiwan Semiconductor Manufacturing Co. fabricates the physical silicon wafers.',
      primarySourceUrl: 'https://investor.nvidia.com/financial-info/sec-filings',
      sourceName: 'NVIDIA SEC Form 10-K & Foundry Disclosures',
      checkedAt: '2026-09-05',
      status: 'verified',
    },
    instrument: ROOM_SIMULATIONS.chip,
  },
  {
    id: 'mug',
    label: 'Ceramic Mug',
    category: 'Daily Ritual & Goods',
    iconName: 'Coffee',
    color: '#ffffff',
    secondaryColor: '#006241',
    geometryType: 'mug',
    anchorSlot: 5, // Desk front-left
    company: {
      id: 'starbucks',
      name: 'Starbucks Corporation',
      ticker: 'SBUX',
      sector: 'Specialty Eateries & Retail',
      summary: 'Premier roaster and retailer of specialty coffee with over 38,000 stores globally.',
      headquarters: 'Seattle, Washington, USA',
      primarySourceUrl: 'https://investor.starbucks.com',
    },
    relationship: {
      id: 'rel_mug_starbucks',
      objectId: 'mug',
      companyId: 'starbucks',
      relationshipType: 'brand_owned_by',
      claim: 'Crafted under Starbucks Global Coffee & Retail Merchandise division, ethical Arabica sourcing verified by C.A.F.E. Practices.',
      explanation:
        'Beyond fresh beverage service, Starbucks designs branded ceramic tableware and packages consumer goods sold worldwide.',
      primarySourceUrl: 'https://stories.starbucks.com/press',
      sourceName: 'Starbucks Investor Relations & Global Factsheet',
      checkedAt: '2026-09-05',
      status: 'verified',
    },
    instrument: ROOM_SIMULATIONS.mug,
  },
];

export const AVAILABLE_INTERESTS = [
  { id: 'design', label: 'Design & Craft', icon: 'Sparkles', suggestedObjectIds: ['laptop', 'mug'] },
  { id: 'tech', label: 'Deep Technology', icon: 'Cpu', suggestedObjectIds: ['laptop', 'chip'] },
  { id: 'gaming', label: 'Play & Gaming', icon: 'Gamepad2', suggestedObjectIds: ['controller', 'screen'] },
  { id: 'cinema', label: 'Film & Media', icon: 'Tv', suggestedObjectIds: ['screen'] },
  { id: 'logistics', label: 'Commerce & Flow', icon: 'Package', suggestedObjectIds: ['parcel'] },
  { id: 'ritual', label: 'Daily Rituals', icon: 'Coffee', suggestedObjectIds: ['mug'] },
];

export const ROOM_ANCHORS = [
  { slotIndex: 0, label: 'Main Desk (Center)', position: [0, 0.65, 0] as const },
  { slotIndex: 1, label: 'Desk Tray (Right)', position: [0.8, 0.65, 0.2] as const },
  { slotIndex: 2, label: 'Low Wooden Shelf', position: [-0.9, 0.35, 0.6] as const },
  { slotIndex: 3, label: 'Floating Wall Frame', position: [0, 1.45, -0.9] as const },
  { slotIndex: 4, label: 'High Porcelain Shelf', position: [0.9, 1.3, -0.6] as const },
  { slotIndex: 5, label: 'Front Coaster', position: [-0.65, 0.65, 0.3] as const },
];
