// Acceptance tests for the core audit findings. No browser wallet or funds used.
const fs=require('node:fs'),path=require('node:path'),ts=require('typescript'),assert=require('node:assert/strict');
function loader(overrides={}){const cache={};function load(file){file=path.resolve(file);if(file in overrides)return overrides[file];if(cache[file])return cache[file].exports;const m={exports:{}};cache[file]=m;const js=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const req=id=>{if(id==='server-only')return {};if(id==='next/server')return {NextResponse:{json:(body,opts)=>({body,status:opts?.status||200})}};if(id.startsWith('.')||id.startsWith('@/')){const base=id.startsWith('@/')?path.resolve(id.slice(2)):path.resolve(path.dirname(file),id);return load(base+'.ts')}return require(id)};new Function('require','module','exports',js)(req,m,m.exports);return m.exports;}return load;}
const ok=result=>({status:'success',result}),fail={status:'failure',error:Error('RPC failure')};const addr='0x0000000000000000000000000000000000000001';const tokens=[{ticker:'TEST',onchainSymbol:'TESTc',name:'Test',token:addr,feed:addr,decimals:8},{ticker:'OTHER',onchainSymbol:'OTHERc',name:'Other',token:'0x0000000000000000000000000000000000000002',feed:addr,decimals:8}];
function mocks(res,priceResult={}){return {[path.resolve('lib/base/client.ts')]:{baseClient:{getBlockNumber:async()=>123n,multicall:async opts=>{assert.equal(opts.blockNumber,123n);return res}}},[path.resolve('lib/base/tokens.ts')]:{TOKENS:tokens},[path.resolve('lib/base/prices.ts')]:{readPrices:async block=>{assert.equal(block,123n);return priceResult}}};}
(async()=>{const model=loader()('lib/base/model.ts');let checks=0;const pass=name=>{checks++;console.log('PASS',name)};
const h={raw:'1000000000',scaledRaw:'2000000000',decimals:8};const p={answerRaw:'20000000000',decimals:8,state:'reference',updatedAt:Date.now(),isStale:false};assert.equal(model.usd(model.positionUsdAtoms(h,p)),'$2,000.00');pass('2:1 split does not double-count multiplier');
const lpModel=loader()('lib/base/lp-model.ts');const band=lpModel.stockBandFromTicks(-11700,-10900);assert.ok(band.low<band.high);assert.equal(lpModel.markerPosition(5,0,10),50);assert.equal(lpModel.markerPosition(-2,0,10),0);assert.equal(lpModel.markerPosition(20,0,10),100);assert.equal(lpModel.stockLpMarket('aapl').pool.toLowerCase(),'0xa3b1e3f9747065e2073722ff4c9027d3ea4994f0');assert.deepEqual(Object.keys(lpModel.STOCK_LP_MARKETS).sort(),['AAPL','AMZN','GOOGL','META','MSFT','MSTR','NVDA','SNDK','SPCX','TSLA']);for(const market of Object.values(lpModel.STOCK_LP_MARKETS)){assert.match(market.pool,/^0x[0-9a-f]{40}$/i);assert.match(market.gauge,/^0x[0-9a-f]{40}$/i)}pass('stock LP registry and range visualization are bounded');
assert.equal(model.usd(model.positionUsdAtoms({...h,raw:'10000000',decimals:6},{...p,answerRaw:'123456',decimals:3})),'$1,234.56');pass('mixed token and oracle decimals');
assert.equal(model.usd(model.positionUsdAtoms({...h,raw:'1',decimals:18},p)),'$0.00');assert.equal(model.usd(0n),'$0.00');pass('dust and exact zero');
let totals=model.portfolio([{...h,ticker:'TEST'},{...h,ticker:'OTHER'}],{TEST:p});assert.equal(totals.missing,1);assert.equal(totals.priced,1);pass('missing price yields explicit incomplete coverage');
assert.equal(model.positionUsdAtoms(h,{...p,state:'paused'}),null);assert.equal(model.priceState({...p,updatedAt:1}).state,'aged');pass('paused excluded and cached freshness recomputed');
const now=Date.now(),sec=BigInt(Math.floor(now/1000));for(const args of [[-1n,sec,1n,1n,8],[0n,sec,1n,1n,8],[1n,sec+1n,1n,1n,8],[1n,0n,1n,1n,8],[1n,sec,2n,1n,8],[1n,sec,1n,1n,99]])assert.equal(model.validRound(...args,now),false);assert.equal(model.validRound(1n,sec,1n,1n,8,now),true);pass('invalid oracle answers, timestamps, rounds and decimals rejected');
const partial=await loader(mocks([ok(1000000000n),ok(2000000000n),ok(8),ok('TESTc'),fail,fail,fail,fail]))('lib/base/holdings.ts').readHoldings(addr);assert.equal(partial.status,'partial');assert.equal(partial.holdings[0].raw,'1000000000');assert.equal(partial.holdings[0].shares,'20');assert.deepEqual(partial.failedTokens,['OTHERc']);pass('partial RPC failure and separate raw/scaled quantities');
await assert.rejects(()=>loader(mocks(Array(8).fill(fail)))('lib/base/holdings.ts').readHoldings(addr));pass('all failed token reads cannot return empty holdings');
const empty=await loader(mocks([ok(0n),ok(0n),ok(8),ok('TESTc'),ok(0n),ok(0n),ok(8),ok('OTHERc')]))('lib/base/holdings.ts').readHoldings(addr);assert.equal(empty.status,'complete');assert.deepEqual(empty.holdings,[]);pass('verified zero holdings remains a legitimate empty state');
const route=loader({[path.resolve('lib/base/holdings.ts')]:{readHoldings:async()=>{throw Error('offline')}}})('app/api/holdings/route.ts');assert.equal((await route.GET(new Request('https://daybreak.test/api/holdings?address=bad'))).status,400);const outage=await route.GET(new Request('https://daybreak.test/api/holdings?address='+addr));assert.equal(outage.status,503);assert.equal(outage.body.holdings,undefined);pass('HTTP validation and outage contract');
const news=loader()('lib/news/provider.ts');process.env.FINNHUB_API_KEY='audit';global.fetch=async()=>({ok:true,json:async()=>[{headline:'Apple unveils new iPhone',url:'https://example.com/apple?utm_source=x',source:'Wire',datetime:1789000000,image:'https://example.com/i.png'},{headline:'Apple unveils new iPhone',url:'https://example.com/apple',source:'Wire',datetime:1789000000},{headline:'x',url:'javascript:alert(1)',source:'X',datetime:1789000000},{headline:'Monster Beverage earnings beat',url:'https://example.com/monster',source:'Wire',datetime:1789000000}]});const feed=await news.fetchCompanyNews('AAPL');assert.equal(feed.articles.length,1);assert.equal(feed.articles[0].url,'https://example.com/apple');assert.equal(feed.articles[0].seenAt,new Date(1789000000*1000).toISOString());assert.equal(feed.stale,false);pass('finnhub normalization: sanitize, dedupe, relevance, dates');
const requests=loader()('lib/server/requests.ts');const cache=requests.createRequestCache(1000,2,1);let count=0;const read=()=>new Promise(resolve=>setTimeout(()=>resolve(++count),10));const [a,b]=await Promise.all([cache('same',read),cache('same',read)]);assert.equal(a,b);assert.equal(count,1);const limited=requests.createRateLimit(2);assert.equal(limited(),true);assert.equal(limited(),true);assert.equal(limited(),false);pass('request coalescing and bounded rate limit');
const registry=loader()('lib/base/tokens.ts');for(const t of registry.TOKENS){const u=new URL(registry.buyUrl(t));assert.equal(u.hostname,'app.uniswap.org');assert.equal(u.searchParams.get('chain'),'base');assert.equal(u.searchParams.get('outputCurrency'),t.token)}assert.throws(()=>registry.buyUrl({token:addr}));pass('outbound buy links bind to allowlisted Base addresses');
const priceMocks=mocks([]);delete priceMocks[path.resolve('lib/base/prices.ts')];priceMocks[path.resolve('lib/base/client.ts')].baseClient.multicall=async()=>[ok([1n,100n,sec,sec,1n]),ok(8),ok('Coinbase TEST'),ok([1n,true]),ok([1n,100n,sec,sec,1n]),ok(8),ok('Wrong oracle'),ok([1n,false])];const validatedPrices=await loader(priceMocks)('lib/base/prices.ts').readPrices();assert.equal(validatedPrices.TEST.state,'paused');assert.equal(validatedPrices.OTHER.state,'unavailable');pass('oracle registry pause and feed identity enforced');
assert.equal((await news.fetchCompanyNews('AAPL')).articles.length,1);pass('company feed stays relevant under the same fetch');
const builder=loader()('lib/openlaunch/builder.ts');assert.equal(builder.tickForStartPrice(1,6,6),0);assert.equal(builder.tickForStartPrice(0.5,6,6),7000);assert.ok(builder.tickForStartPrice(30000/1e9/200,6,18)>400000);assert.equal(builder.priceForTick(0,6,6),1);assert.equal(builder.parseSupplyHuman('1000000000'),1000000000000000000000000000n);assert.throws(()=>builder.encodeSplit([{payout:addr,bps:9999}]));assert.throws(()=>builder.tickForStartPrice(-1,6,6));pass('launch math direction, exact supply, split validation');
const stonk=loader()('lib/stonkfun/client.ts'),bs58=require('bs58').default;const sig=Uint8Array.from({length:64},(_,i)=>i+1),signed=Buffer.concat([Buffer.from([1]),Buffer.from(sig),Buffer.from([0])]).toString('base64');assert.equal(stonk.signedTransactionSignature(signed),bs58.encode(sig));assert.throws(()=>stonk.signedTransactionSignature(Buffer.concat([Buffer.from([1]),Buffer.alloc(64),Buffer.from([0])]).toString('base64')));pass('Solana payment signature is recoverable before submit');
const {QueryClient,QueryObserver}=require('@tanstack/react-query');const qc=new QueryClient();qc.setQueryData(['holdings',8453,'wallet-a'],{address:'wallet-a',holdings:[h]});const observer=new QueryObserver(qc,{queryKey:['holdings',8453,'wallet-a'],enabled:false});assert.equal(observer.getCurrentResult().data.address,'wallet-a');observer.setOptions({queryKey:['holdings',8453,'wallet-b'],enabled:false});assert.equal(observer.getCurrentResult().data,undefined);observer.destroy();qc.clear();pass('wallet query key switch does not retain previous account data');
const accountCache=loader()('lib/account/cache.ts');const accountA=accountCache.accountQueryKey('did:privy:a'),accountB=accountCache.accountQueryKey('did:privy:b');assert.notDeepEqual(accountA,accountB);qc.setQueryData(accountA,{userId:'a'});const accountObserver=new QueryObserver(qc,{queryKey:accountB,enabled:false});assert.equal(accountObserver.getCurrentResult().data,undefined);accountObserver.destroy();qc.clear();pass('account cache is isolated by verified Privy identity');
const keyed=requests.createKeyedRateLimit(2,60000,2);assert.equal(keyed('a'),true);assert.equal(keyed('a'),true);assert.equal(keyed('a'),false);assert.equal(keyed('b'),true);pass('account write rate limits are isolated per identity');
const otherAddress='0x0000000000000000000000000000000000000003',secondMeme='0x0000000000000000000000000000000000000005';const memeMocks={[path.resolve('lib/base/tokens.ts')]:{TOKENS:[tokens[0]],tokenForTicker:()=>tokens[0]}};const memes=loader(memeMocks)('lib/base/memecoins.ts');global.fetch=async()=>({ok:true,json:async()=>({pairs:[{chainId:'base',baseToken:{address:addr,symbol:'TESTc'},quoteToken:{address:otherAddress,symbol:'MEME',name:'Meme'},priceUsd:'200',liquidity:{usd:9000},volume:{h24:200}},{chainId:'base',baseToken:{address:secondMeme,symbol:'MEME2',name:'Meme two'},quoteToken:{address:addr,symbol:'TESTc'},priceUsd:'0.25',liquidity:{usd:9000},volume:{h24:300}},{chainId:'base',baseToken:{address:otherAddress,symbol:'FAKE'},quoteToken:{address:'0x0000000000000000000000000000000000000004',symbol:'USDC'},priceUsd:'99',liquidity:{usd:9000},volume:{h24:400}}]})});const memeRows=await memes.fetchMemeTokens('TEST');assert.equal(memeRows.length,2);assert.equal(memeRows.find(x=>x.address===otherAddress).priceUsd,null);assert.equal(memeRows.find(x=>x.address===secondMeme).priceUsd,0.25);pass('memestock pairing requires the stock and prices only the reported base token');
global.fetch=async()=>({ok:false,status:429});await assert.rejects(()=>memes.fetchMemeTokens('TEST'),e=>e.name==='MemeProviderError');await assert.rejects(()=>memes.fetchTrending(),e=>e.name==='MemeProviderError');pass('memestock provider outages propagate instead of becoming empty feeds');
const auth=loader()('lib/account/auth-server.ts');assert.throws(()=>auth.requireActiveAccount({status:'suspended'}),e=>e.status===403);await assert.rejects(()=>auth.readJsonObject(new Request('https://daybreak.test/api/me',{method:'POST',body:'[]'})),e=>e.status===400);await assert.rejects(()=>auth.readJsonObject(new Request('https://daybreak.test/api/me',{method:'POST',body:'x'.repeat(17000)})),e=>e.status===413);pass('suspended accounts and malformed or oversized bodies are rejected');
const schemaMarkers={users:{},profiles:{},bookmarks:{companyId:{},userId:{}},circles:{},circleMemberships:{},migrationImports:{id:{}}};let bookmarkWrites=0,claim=true;const chain=(final)=>({values(){return this},onConflictDoNothing(){return this},returning:async()=>final});const tx={execute:async()=>[],insert(table){if(table===schemaMarkers.migrationImports)return chain(claim?[{id:'claim'}]:[]);if(table===schemaMarkers.bookmarks){bookmarkWrites++;return chain([])}return chain([])},select(){return{from(){return{where:async()=>[]}}}},update(){return{set(){return{where:async()=>[]}}}}};const fakeDb={insert(){return chain([])},transaction:fn=>fn(tx)};const repo=loader({[path.resolve('lib/db/client.ts')]:{getDb:()=>fakeDb},[path.resolve('lib/db/schema.ts')]:schemaMarkers,[path.resolve('lib/db/circles.ts')]:{CIRCLES:[],CIRCLE_SLUGS:[]},[path.resolve('lib/catalog.ts')]:{DISCOVERY_CATALOG:[]},[path.resolve('lib/base/tokens.ts')]:{TOKENS:[tokens[0]]}})('lib/db/repo.ts');const firstImport=await repo.importLocal('user',{bookmarks:['TEST'],memberships:[]},'guest-v1');assert.equal(firstImport.alreadyImported,false);assert.equal(bookmarkWrites,1);claim=false;const duplicateImport=await repo.importLocal('user',{bookmarks:['TEST'],memberships:[]},'guest-v1');assert.equal(duplicateImport.alreadyImported,true);assert.equal(bookmarkWrites,1);pass('local import atomically claims one server-controlled version before writes');
await import('@coinbase/wallet-sdk');pass('Coinbase SDK runtime import resolves');console.log(`${checks} acceptance groups passed`);
})().catch(e=>{console.error(e);process.exitCode=1});
