// Acceptance tests for the core audit findings. No browser wallet or funds used.
const fs=require('node:fs'),path=require('node:path'),ts=require('typescript'),assert=require('node:assert/strict');
function loader(overrides={}){const cache={};function load(file){file=path.resolve(file);if(file in overrides)return overrides[file];if(cache[file])return cache[file].exports;const m={exports:{}};cache[file]=m;const js=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const req=id=>{if(id==='server-only')return {};if(id==='next/server')return {NextResponse:{json:(body,opts)=>({body,status:opts?.status||200})}};if(id.startsWith('.')||id.startsWith('@/')){const base=id.startsWith('@/')?path.resolve(id.slice(2)):path.resolve(path.dirname(file),id);return load(base+'.ts')}return require(id)};new Function('require','module','exports',js)(req,m,m.exports);return m.exports;}return load;}
const ok=result=>({status:'success',result}),fail={status:'failure',error:Error('RPC failure')};const addr='0x0000000000000000000000000000000000000001';const tokens=[{ticker:'TEST',onchainSymbol:'TESTc',name:'Test',token:addr,feed:addr,decimals:8},{ticker:'OTHER',onchainSymbol:'OTHERc',name:'Other',token:'0x0000000000000000000000000000000000000002',feed:addr,decimals:8}];
function mocks(res,priceResult={}){return {[path.resolve('lib/base/client.ts')]:{baseClient:{getBlockNumber:async()=>123n,multicall:async opts=>{assert.equal(opts.blockNumber,123n);return res}}},[path.resolve('lib/base/tokens.ts')]:{TOKENS:tokens},[path.resolve('lib/base/prices.ts')]:{readPrices:async block=>{assert.equal(block,123n);return priceResult}}};}
(async()=>{const model=loader()('lib/base/model.ts');let checks=0;const pass=name=>{checks++;console.log('PASS',name)};
const h={raw:'1000000000',scaledRaw:'2000000000',decimals:8};const p={answerRaw:'20000000000',decimals:8,state:'reference',updatedAt:Date.now(),isStale:false};assert.equal(model.usd(model.positionUsdAtoms(h,p)),'$2,000.00');pass('2:1 split does not double-count multiplier');
assert.equal(model.usd(model.positionUsdAtoms({...h,raw:'10000000',decimals:6},{...p,answerRaw:'123456',decimals:3})),'$1,234.56');pass('mixed token and oracle decimals');
assert.equal(model.usd(model.positionUsdAtoms({...h,raw:'1',decimals:18},p)),'$0.00');assert.equal(model.usd(0n),'$0.00');pass('dust and exact zero');
let totals=model.portfolio([{...h,ticker:'TEST'},{...h,ticker:'OTHER'}],{TEST:p});assert.equal(totals.missing,1);assert.equal(totals.priced,1);pass('missing price yields explicit incomplete coverage');
assert.equal(model.positionUsdAtoms(h,{...p,state:'paused'}),null);assert.equal(model.priceState({...p,updatedAt:1}).state,'aged');pass('paused excluded and cached freshness recomputed');
const now=Date.now(),sec=BigInt(Math.floor(now/1000));for(const args of [[-1n,sec,1n,1n,8],[0n,sec,1n,1n,8],[1n,sec+1n,1n,1n,8],[1n,0n,1n,1n,8],[1n,sec,2n,1n,8],[1n,sec,1n,1n,99]])assert.equal(model.validRound(...args,now),false);assert.equal(model.validRound(1n,sec,1n,1n,8,now),true);pass('invalid oracle answers, timestamps, rounds and decimals rejected');
const partial=await loader(mocks([ok(1000000000n),ok(2000000000n),ok(8),ok('TESTc'),fail,fail,fail,fail]))('lib/base/holdings.ts').readHoldings(addr);assert.equal(partial.status,'partial');assert.equal(partial.holdings[0].raw,'1000000000');assert.equal(partial.holdings[0].shares,'20');assert.deepEqual(partial.failedTokens,['OTHERc']);pass('partial RPC failure and separate raw/scaled quantities');
await assert.rejects(()=>loader(mocks(Array(8).fill(fail)))('lib/base/holdings.ts').readHoldings(addr));pass('all failed token reads cannot return empty holdings');
const empty=await loader(mocks([ok(0n),ok(0n),ok(8),ok('TESTc'),ok(0n),ok(0n),ok(8),ok('OTHERc')]))('lib/base/holdings.ts').readHoldings(addr);assert.equal(empty.status,'complete');assert.deepEqual(empty.holdings,[]);pass('verified zero holdings remains a legitimate empty state');
const route=loader({[path.resolve('lib/base/holdings.ts')]:{readHoldings:async()=>{throw Error('offline')}}})('app/api/holdings/route.ts');assert.equal((await route.GET(new Request('https://daybreak.test/api/holdings?address=bad'))).status,400);const outage=await route.GET(new Request('https://daybreak.test/api/holdings?address='+addr));assert.equal(outage.status,503);assert.equal(outage.body.holdings,undefined);pass('HTTP validation and outage contract');
const news=loader()('lib/news/provider.ts');const articles=news.normalizeArticles({articles:[{title:'unsafe',url:'javascript:alert(1)'},{title:'valid',url:'https://example.com/story?utm_source=test',seendate:'20260906T010203Z'},{title:'duplicate',url:'https://example.com/story'}]});assert.equal(articles.length,1);assert.equal(articles[0].seenAt,'2026-09-06T01:02:03.000Z');pass('news links sanitized, deduplicated and dates normalized');
const requests=loader()('lib/server/requests.ts');const cache=requests.createRequestCache(1000,2,1);let count=0;const read=()=>new Promise(resolve=>setTimeout(()=>resolve(++count),10));const [a,b]=await Promise.all([cache('same',read),cache('same',read)]);assert.equal(a,b);assert.equal(count,1);const limited=requests.createRateLimit(2);assert.equal(limited(),true);assert.equal(limited(),true);assert.equal(limited(),false);pass('request coalescing and bounded rate limit');
const registry=loader()('lib/base/tokens.ts');for(const t of registry.TOKENS){const u=new URL(registry.buyUrl(t));assert.equal(u.hostname,'app.uniswap.org');assert.equal(u.searchParams.get('chain'),'base');assert.equal(u.searchParams.get('outputCurrency'),t.token)}assert.throws(()=>registry.buyUrl({token:addr}));pass('outbound buy links bind to allowlisted Base addresses');
const priceMocks=mocks([]);delete priceMocks[path.resolve('lib/base/prices.ts')];priceMocks[path.resolve('lib/base/client.ts')].baseClient.multicall=async()=>[ok([1n,100n,sec,sec,1n]),ok(8),ok('Coinbase TEST'),ok([1n,true]),ok([1n,100n,sec,sec,1n]),ok(8),ok('Wrong oracle'),ok([1n,false])];const validatedPrices=await loader(priceMocks)('lib/base/prices.ts').readPrices();assert.equal(validatedPrices.TEST.state,'paused');assert.equal(validatedPrices.OTHER.state,'unavailable');pass('oracle registry pause and feed identity enforced');
assert.equal(news.normalizeArticles({articles:[{title:'Unrelated market report',url:'https://example.com/unrelated'},{title:'Apple unveils new iPhone',url:'https://example.com/apple'}]},'AAPL').length,1);pass('company headline relevance filter');
const {QueryClient,QueryObserver}=require('@tanstack/react-query');const qc=new QueryClient();qc.setQueryData(['holdings',8453,'wallet-a'],{address:'wallet-a',holdings:[h]});const observer=new QueryObserver(qc,{queryKey:['holdings',8453,'wallet-a'],enabled:false});assert.equal(observer.getCurrentResult().data.address,'wallet-a');observer.setOptions({queryKey:['holdings',8453,'wallet-b'],enabled:false});assert.equal(observer.getCurrentResult().data,undefined);observer.destroy();qc.clear();pass('wallet query key switch does not retain previous account data');
await import('@coinbase/wallet-sdk');pass('Coinbase SDK runtime import resolves');console.log(`${checks} acceptance groups passed`);
})().catch(e=>{console.error(e);process.exitCode=1});
